export const BIBLE_STRUCTURE = [
  { book: 'Gênesis', chapters: 50, testament: 'old' },
  { book: 'Êxodo', chapters: 40, testament: 'old' },
  { book: 'Levítico', chapters: 27, testament: 'old' },
  { book: 'Números', chapters: 36, testament: 'old' },
  { book: 'Deuteronômio', chapters: 34, testament: 'old' },
  { book: 'Josué', chapters: 24, testament: 'old' },
  { book: 'Juízes', chapters: 21, testament: 'old' },
  { book: 'Rute', chapters: 4, testament: 'old' },
  { book: '1 Samuel', chapters: 31, testament: 'old' },
  { book: '2 Samuel', chapters: 24, testament: 'old' },
  { book: '1 Reis', chapters: 22, testament: 'old' },
  { book: '2 Reis', chapters: 25, testament: 'old' },
  { book: '1 Crônicas', chapters: 29, testament: 'old' },
  { book: '2 Crônicas', chapters: 36, testament: 'old' },
  { book: 'Esdras', chapters: 10, testament: 'old' },
  { book: 'Neemias', chapters: 13, testament: 'old' },
  { book: 'Ester', chapters: 10, testament: 'old' },
  { book: 'Jó', chapters: 42, testament: 'old' },
  { book: 'Salmos', chapters: 150, testament: 'old' },
  { book: 'Provérbios', chapters: 31, testament: 'old' },
  { book: 'Eclesiastes', chapters: 12, testament: 'old' },
  { book: 'Cantares', chapters: 8, testament: 'old' },
  { book: 'Isaías', chapters: 66, testament: 'old' },
  { book: 'Jeremias', chapters: 52, testament: 'old' },
  { book: 'Lamentações', chapters: 5, testament: 'old' },
  { book: 'Ezequiel', chapters: 48, testament: 'old' },
  { book: 'Daniel', chapters: 12, testament: 'old' },
  { book: 'Oséias', chapters: 14, testament: 'old' },
  { book: 'Joel', chapters: 3, testament: 'old' },
  { book: 'Amós', chapters: 9, testament: 'old' },
  { book: 'Obadias', chapters: 1, testament: 'old' },
  { book: 'Jonas', chapters: 4, testament: 'old' },
  { book: 'Miquéias', chapters: 7, testament: 'old' },
  { book: 'Naum', chapters: 3, testament: 'old' },
  { book: 'Habacuque', chapters: 3, testament: 'old' },
  { book: 'Sofonias', chapters: 3, testament: 'old' },
  { book: 'Ageu', chapters: 2, testament: 'old' },
  { book: 'Zacarias', chapters: 14, testament: 'old' },
  { book: 'Malaquias', chapters: 4, testament: 'old' },
  { book: 'Mateus', chapters: 28, testament: 'new' },
  { book: 'Marcos', chapters: 16, testament: 'new' },
  { book: 'Lucas', chapters: 24, testament: 'new' },
  { book: 'João', chapters: 21, testament: 'new' },
  { book: 'Atos', chapters: 28, testament: 'new' },
  { book: 'Romanos', chapters: 16, testament: 'new' },
  { book: '1 Coríntios', chapters: 16, testament: 'new' },
  { id: '2corinthians', book: '2 Coríntios', chapters: 13, testament: 'new' },
  { book: 'Gálatas', chapters: 6, testament: 'new' },
  { book: 'Efésios', chapters: 6, testament: 'new' },
  { book: 'Filipenses', chapters: 4, testament: 'new' },
  { book: 'Colossenses', chapters: 4, testament: 'new' },
  { book: '1 Tessalonicenses', chapters: 5, testament: 'new' },
  { book: '2 Tessalonicenses', chapters: 3, testament: 'new' },
  { book: '1 Timóteo', chapters: 6, testament: 'new' },
  { book: '2 Timóteo', chapters: 4, testament: 'new' },
  { book: 'Tito', chapters: 3, testament: 'new' },
  { book: 'Filemom', chapters: 1, testament: 'new' },
  { book: 'Hebreus', chapters: 13, testament: 'new' },
  { book: 'Tiago', chapters: 5, testament: 'new' },
  { book: '1 Pedro', chapters: 5, testament: 'new' },
  { book: '2 Pedro', chapters: 3, testament: 'new' },
  { book: '1 João', chapters: 5, testament: 'new' },
  { book: '2 João', chapters: 1, testament: 'new' },
  { book: '3 João', chapters: 1, testament: 'new' },
  { book: 'Judas', chapters: 1, testament: 'new' },
  { book: 'Apocalipse', chapters: 22, testament: 'new' }
];

export const SAMPLE_VERSES: Record<string, string> = {
  'João 3:16': 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crer não pereça, mas tenha a vida eterna.',
  'Salmos 23:1': 'O Senhor é o meu pastor, nada me faltará.',
  'Efésios 6:10': 'No demais, irmãos meus, fortalecei-vos no Senhor e na força do seu poder.',
  'Mateus 5:1': 'E Jesus, vendo a multidão, subiu a um monte, e, assentando-se, aproximaram-se dele os seus discípulos.',
  'Gênesis 1:1': 'No princípio criou Deus o céu e a terra.'
};
